/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFT {
  tokenId: string;
  metadata: any;
  valuation: any;
}

export interface PortfolioHolding {
  userId: string;
  nftId: string;
  quantity: number;
}

export interface User {
  userId: string;
}

export interface MarketData {
  tokenId: string;
  price: any;
  volume: any;
}

export interface RiskThreshold {
  thresholdId: string;
  riskLevel: string;
  percentage: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
