/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTCollection {
  id: string;
  name: string;
  contractAddress: string;
}

export interface NFTHolding {
  id: string;
  nftCollectionId: string;
  quantity: number;
  lastUpdated: string;
}

export interface Portfolio {
  id: string;
  userId: string;
  createdAt: string;
}

export interface PriceFeed {
  id: string;
  asset: string;
  price: number;
  timestamp: string;
}

export interface User {
  id: string;
  username: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
