/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTPortfolio {
  id: string;
  userId: string;
  nftPositions: any;
  riskProfile: string;
  createdAt: string;
}

export interface NFTPosition {
  id: string;
  nftAsset: string;
  quantity: number;
  entryPrice: number;
  currentPrice: number;
  portfolioId: string;
  createdAt: string;
}

export interface MarketData {
  id: string;
  asset: string;
  timestamp: string;
  price: number;
  volume: number;
  change: number;
  createdAt: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
