/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFT {
  tokenId: string;
  name: string;
  symbol: string;
  metadata: any;
}

export interface Portfolio {
  portfolioId: string;
  userId: string;
  createdAt: string;
}

export interface TradingSession {
  sessionId: string;
  nftId: string;
  timestamp: string;
  price: number;
}

export interface User {
  userId: string;
  username: string;
  password: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
