/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface User {
  id: string;
  createdAt: string;
}

export interface SentimentAnalysisResult {
  id: string;
  userId: string;
  sentimentScore: number;
}

export interface SecurityAlert {
  id: string;
  userId: string;
  alertType: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
