/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface Vault {
  id: string;
  userId: string;
  ptBalance: number;
  riskProfile: string;
  createdAt: string;
}

export interface User {
  id: string;
  nftId: string;
  createdAt: string;
}

export interface Asset {
  id: string;
  name: string;
  symbol: string;
  price: number;
  quantity: number;
}

export interface GPTResponse {
  id: string;
  timestamp: string;
  recommendation: string;
  riskAssessment: string;
  confidenceScore: number;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
