/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface User {
  id: string;
  address: string;
  createdAt: string;
}

export interface Model {
  id: string;
  name: string;
  description: string;
  nvcModelId: string;
  createdAt: string;
}

export interface Transaction {
  id: string;
  timestamp: string;
  modelId: string;
  userId: string;
  amount: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
