/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTHolder {
  id: string;
  username: string;
  createdAt: string;
}

export interface MosslandNFT {
  tokenId: string;
  ownerId: string;
  price: any;
  createdAt: string;
}

export interface Portfolio {
  id: string;
  userId: string;
  createdAt: string;
}

export interface ValuationData {
  tokenId: string;
  timestamp: string;
  price: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
