/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface SmartContract {
  id: string;
  contractAddress: string;
  code: string;
  riskScore: number;
  vulnerabilities: any;
}

export interface Vulnerability {
  id: string;
  contractId: string;
  description: string;
  severity: string;
  remediationSuggestion: string;
}

export interface LLMAnalysis {
  id: string;
  contractId: string;
  analysisResult: string;
  timestamp: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
