/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface RWA Asset {
  id: string;
  name: string;
  symbol: string;
  price: number;
  blockchain: string;
}

export interface Portfolio {
  id: string;
  name: string;
  riskTolerance: string;
  assetAllocation: any;
}

export interface GPT-5 Agent {
  id: string;
  prompt: string;
}

export interface NFT Holder {
  nft_id: string;
  wallet_address: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
