/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFT Withdrawal Transaction {
  id: string;
  nftAddress: string;
  senderAddress: string;
  timestamp: string;
  status: string;
}

export interface Smart Contract {
  contractAddress: string;
  contractName: string;
}

export interface Claude Opus Response {
  responseCode: number;
  responseText: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
