/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface UserSettings {
  userId: string;
  themePreferences: any;
  accessibilitySettings: any;
}

export interface BlockchainInteraction {
  interactionId: string;
  userId: string;
  blockchainNetwork: string;
  interactionType: string;
  timestamp: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
