/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTCollection {
  id: string;
  name: string;
  contractAddress: string;
  tokenId: string;
}

export interface Portfolio {
  id: string;
  userId: string;
  totalValue: number;
}

export interface NFTTransaction {
  id: string;
  portfolioId: string;
  nftCollectionId: string;
  quantity: number;
  transactionTimestamp: string;
}

export interface RiskAssessment {
  id: string;
  portfolioId: string;
  gpt5Output: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
