/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTHolder {
  walletAddress: string;
  nftToken: string;
  ownershipCount: number;
}

export interface RiskScore {
  walletAddress: string;
  score: number;
  timestamp: string;
}

export interface MarketData {
  assetAddress: string;
  price: number;
  volatility: number;
}

export interface ClaudeAgentPrompt {
  promptText: string;
  promptVersion: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
