/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFT {
  id: string;
  tokenId: string;
  metadata: Record<string, any>;
  owner: any;
  createdAt: string;
}

export interface User {
  id: string;
  address: any;
  createdAt: string;
}

export interface Prompt {
  id: string;
  text: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
