/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTFraction {
  tokenId: string;
  totalSupply: any;
  owner: any;
  fractionValue: any;
}

export interface Portfolio {
  userId: any;
  name: string;
  riskProfile: string;
}

export interface User {
  address: any;
  username: string;
}

export interface PriceFeed {
  asset: string;
  price: any;
  timestamp: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
