/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTHolder {
  id: string;
  nftAddress: string;
  rainBalance: number;
}

export interface MarketData {
  id: string;
  timestamp: string;
  assetPrice: number;
  volume: number;
}

export interface Portfolio {
  id: string;
  nftHolderId: string;
  rainBalance: number;
  nftAssetAllocation: any;
}

export interface SmartContract {
  id: string;
  contractAddress: string;
  functionName: string;
  parameters: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
