/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface AgentReceipt {
  id: string;
  tokenId: string;
  asset: string;
  quantity: any;
  timestamp: string;
  verifier: string;
}

export interface Portfolio {
  id: string;
  userId: string;
  riskLevel: any;
}

export interface AavePosition {
  id: string;
  asset: string;
  quantity: any;
  borrowRate: any;
}

export interface CompoundPosition {
  id: string;
  asset: string;
  quantity: any;
  interestRate: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
