/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFT {
  tokenId: string;
  name: string;
  symbol: string;
  metadata: any;
  floorPrice: number;
  createdAt: string;
}

export interface User {
  userId: string;
  riskTolerance: string;
  nftHoldings: any;
}

export interface YieldFarmPosition {
  positionId: string;
  nftId: string;
  protocol: string;
  amount: number;
  yieldRate: number;
}

export interface PriceFeed {
  feedId: string;
  asset: string;
  price: number;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
