/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface ENS Domain {
  id: string;
  name: string;
  owner: any;
  registrationStatus: string;
}

export interface NFT {
  id: string;
  tokenId: string;
  metadata: any;
  ensDomainId: string;
}

export interface ClaudeAsset {
  id: string;
  brandName: string;
  assetType: string;
  assetData: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
