from sqlalchemy import Column, Integer, String, Float, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import back_populates
from uuid import uuid4
from datetime import datetime

Base = declarative_base()

class NfTPosition(Base):
    """
    Represents a user's holdings of Mossland NFTs within a DeFi protocol.
    """
    __tablename__ = 'nft_position'

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    nftId = Column(String, nullable=False)
    protocol = Column(String, nullable=False)
    quantity = Column(Integer, nullable=False)
    lastUpdated = Column(DateTime, default=datetime.utcnow())

    def __repr__(self):
        return f"<NfTPosition(id={self.id}, nftId={self.nftId}, protocol={self.protocol}, quantity={self.quantity})>"

class RiskProfile(Base):
    """
    Defines the user's risk tolerance for DeFi portfolio management.
    """
    __tablename__ = 'risk_profile'

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    name = Column(String, nullable=False)
    maxVolatility = Column(Float, nullable=False)
    liquidityThreshold = Column(Float, nullable=False)

    def __repr__(self):
        return f"<RiskProfile(id={self.id}, name={self.name}, maxVolatility={self.maxVolatility}, liquidityThreshold={self.liquidityThreshold})>"

class DeFiProtocol(Base):
    """
    Represents a supported DeFi protocol for portfolio management.
    """
    __tablename__ = 'defi_protocol'

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    name = Column(String, nullable=False)
    apiEndpoint = Column(String, nullable=False)

    def __repr__(self):
        return f"<DeFiProtocol(id={self.id}, name={self.name}, apiEndpoint={self.apiEndpoint})>"

class RebalancingStrategy(Base):
    """
    Represents a suggested rebalancing strategy generated by the GPT-5 agent.
    """
    __tablename__ = 'rebalancing_strategy'

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    protocol = Column(String, nullable=False)
    newQuantity = Column(Integer, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow())

    def __repr__(self):
        return f"<RebalancingStrategy(id={self.id}, protocol={self.protocol}, newQuantity={self.newQuantity}, timestamp={self.timestamp})>"

if __name__ == '__main__':
    Base.metadata.create_all(engine)