from sqlalchemy import Column, String, Float, DateTime, Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import back_populates
from uuid import uuid4
from datetime import datetime

Base = declarative_base()

class SmartContract(Base):
    """
    Represents a Mossland NFT smart contract.
    """
    __tablename__ = 'smart_contracts'

    id = Column(UUID, primary_key=True, default=uuid4)
    contractAddress = Column(String, nullable=False)
    contractName = Column(String, nullable=False)
    contractVersion = Column(String, nullable=False)
    creationTimestamp = Column(DateTime, nullable=False)
    updated_at = Column(DateTime, onupdate=True)
    created_at = Column(DateTime, server_default=datetime.utcnow)

    def __repr__(self):
        return f"<SmartContract(id={self.id}, contractAddress='{self.contractAddress}')>"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if 'id' not in kwargs:
            self.id = uuid4()


class VulnerabilityReport(Base):
    """
    Represents a vulnerability report generated by the AI analysis.
    """
    __tablename__ = 'vulnerability_reports'

    id = Column(UUID, primary_key=True, default=uuid4)
    contractAddress = Column(String, nullable=False)
    vulnerabilityType = Column(String, nullable=False)
    severity = Column(String, nullable=False)
    description = Column(String, nullable=False)
    confidenceScore = Column(Float, nullable=False)
    createdAt = Column(DateTime, nullable=False)
    updated_at = Column(DateTime, onupdate=True)
    created_at = Column(DateTime, server_default=datetime.utcnow)

    def __repr__(self):
        return f"<VulnerabilityReport(id={self.id}, contractAddress='{self.contractAddress}')>"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if 'id' not in kwargs:
            self.id = uuid4()
    
    back_populates = {
        'smart_contract': 'smart_contracts.id'
    }


class RiskAssessment(Base):
    """
    Represents a dynamic risk assessment for a smart contract.
    """
    __tablename__ = 'risk_assessments'

    id = Column(UUID, primary_key=True, default=uuid4)
    contractAddress = Column(String, nullable=False)
    assessmentTimestamp = Column(DateTime, nullable=False)
    overallRiskScore = Column(Float, nullable=False)
    riskFactors = Column(String, nullable=False)
    updated_at = Column(DateTime, onupdate=True)
    created_at = Column(DateTime, server_default=datetime.utcnow)

    def __repr__(self):
        return f"<RiskAssessment(id={self.id}, contractAddress='{self.contractAddress}')>"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if 'id' not in kwargs:
            self.id = uuid4()
    
    back_populates = {
        'smart_contract': 'smart_contracts.id'
    }

# Example usage (not part of the model definition)
# from sqlalchemy import create_engine
# engine = create_engine('postgresql://user:password@host:port/database')
# Base.metadata.create_all(engine)