from sqlalchemy import Column, Integer, String, DateTime, Float, JSON, UUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import back_populates

Base = declarative_base()

class NFTHolder(Base):
    """
    Represents a Mossland NFT holder within the TerraForm system.
    """
    __tablename__ = 'nfts_holder'

    id = Column(UUID, primary_key=True)
    nftAddress = Column(String, nullable=False)
    preferences = Column(JSON, nullable=True)
    created_at = Column(DateTime, server_default=DateTime.utcnow)
    updated_at = Column(DateTime, server_default=DateTime.utcnow, onupdate=True)

    def __repr__(self):
        return f"<NFTHolder(id={self.id}, nftAddress={self.nftAddress})>"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if 'id' not in kwargs:
            self.id = UUID()


class Portfolio(Base):
    """
    Represents the DeFi portfolio managed by a TerraForm agent for a specific NFT holder.
    """
    __tablename__ = 'portfolios'

    id = Column(UUID, primary_key=True)
    nftHolderId = Column(String, nullable=False)
    assetPositions = Column(JSON, nullable=True)
    created_at = Column(DateTime, server_default=DateTime.utcnow)
    updated_at = Column(DateTime, server_default=DateTime.utcnow, onupdate=True)

    def __repr__(self):
        return f"<Portfolio(id={self.id}, nftHolderId={self.nftHolderId})>"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if 'id' not in kwargs:
            self.id = UUID()
    back_populates = 'NFTHolder'


class AssetPosition(Base):
    """
    Represents a single asset held within a portfolio.
    """
    __tablename__ = 'asset_positions'

    id = Column(UUID, primary_key=True)
    assetAddress = Column(String, nullable=False)
    quantity = Column(Float, nullable=False)
    price = Column(Float, nullable=False)
    portfolioId = Column(String, nullable=False)
    created_at = Column(DateTime, server_default=DateTime.utcnow)
    updated_at = Column(DateTime, server_default=DateTime.utcnow, onupdate=True)

    def __repr__(self):
        return f"<AssetPosition(id={self.id}, assetAddress={self.assetAddress})>"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if 'id' not in kwargs:
            self.id = UUID()
    back_populates = 'Portfolio'


class GPT5Recommendation(Base):
    """
    Stores recommendations generated by the GPT-5 API for portfolio rebalancing.
    """
    __tablename__ = 'gpt5_recommendations'

    id = Column(UUID, primary_key=True)
    portfolioId = Column(String, nullable=False)
    recommendation = Column(String, nullable=False)
    timestamp = Column(DateTime, nullable=False)
    created_at = Column(DateTime, server_default=DateTime.utcnow)
    updated_at = Column(DateTime, server_default=DateTime.utcnow, onupdate=True)

    def __repr__(self):
        return f"<GPT5Recommendation(id={self.id}, portfolioId={self.portfolioId})>"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if 'id' not in kwargs:
            self.id = UUID()
    back_populates = 'Portfolio'

if __name__ == '__main__':
    # Example usage
    from sqlalchemy import create_engine
    engine = create_engine('postgresql://user:password@host:port/database')
    Base.metadata.create_all(bind=engine)

    nfts_holder = NFTHolder(nftAddress='0x...', preferences={'risk_tolerance': 'high'})
    portfolio = Portfolio(nftHolderId=nfts_holder.id, assetPositions=[{'assetAddress': '0x...', 'quantity': 10.0, 'price': 100.0}])
    asset_position = AssetPosition(assetAddress='0x...', quantity=5.0, price=50.0, portfolioId=portfolio.id)
    gpt5_recommendation = GPT5Recommendation(portfolioId=portfolio.id, recommendation='Rebalance portfolio', timestamp=datetime.datetime.now())

    print(nfts_holder)
    print(portfolio)
    print(asset_position)
    print(gpt5_recommendation)