from typing import List, Optional
from pydantic import BaseModel, Field
from pydantic import ConfigDict
from datetime import datetime

class FieldValidator(BaseModel):
    """Base class for field validators."""
    value: any
    message: str

    def validate(self, value: any) -> any:
        if value != self.value:
            raise ValueError(self.message)
        return value


class Config:
    """Pydantic Config class."""
    extra = 'forbid'
    allow_population_by_field_name = True
    arbitrary_types_allowed = True


class Asset(BaseModel):
    """Represents a DeFi asset (e.g., USDC, USDT) within the TerraForm system."""
    id: str = Field(..., description="Unique identifier for the asset", min_length=36)
    name: str = Field(..., description="Name of the asset (e.g., USDC, USDT)")
    symbol: str = Field(..., description="Asset symbol (e.g., USDC, USDT)")
    decimals: int = Field(18, description="Number of decimal places")
    config = Config()


class Portfolio(BaseModel):
    """Represents the DeFi position of an NFT holder."""
    nft_holder_id: str = Field(..., description="Unique identifier for the NFT holder")
    assets: List[Asset] = Field([], description="List of assets in the portfolio")
    total_value: float = Field(0.0, description="Total value of the portfolio")
    config = Config()


class RebalancingRecommendation(BaseModel):
    """Represents a recommendation generated by GPT-5 for portfolio adjustments."""
    id: str = Field(..., description="Unique identifier for the recommendation", min_length=36)
    nft_holder_id: str = Field(..., description="Unique identifier for the NFT holder")
    timestamp: datetime = Field(datetime.now, description="Timestamp of the recommendation")
    recommendation: str = Field(..., description="GPT-5 recommendation text")
    confidence: float = Field(0.8, description="Confidence level of the recommendation (0.0-1.0)")
    config = Config()


class NFTHolder(BaseModel):
    """Represents a Mossland NFT holder within the TerraForm system."""
    id: str = Field(..., description="Unique identifier for the NFT holder", min_length=36)
    name: str = Field(..., description="Name of the NFT holder")
    nft_token_address: str = Field(..., description="NFT token address")
    portfolio: Optional[Portfolio] = Field(None, description="Portfolio of the NFT holder")
    config = Config()


class CreateNFTHolder(BaseModel):
    """Create request for NFTHolder."""
    name: str = Field(..., description="Name of the NFT holder")
    nft_token_address: str = Field(..., description="NFT token address")
    config = Config()


class UpdateNFTHolder(BaseModel):
    """Update request for NFTHolder."""
    name: Optional[str] = Field(None, description="Name of the NFT holder")
    nft_token_address: Optional[str] = Field(None, description="NFT token address")
    config = Config()


class ResponseNFTHolder(BaseModel):
    """Response schema for NFTHolder."""
    id: str
    name: str
    nft_token_address: str
    portfolio: Optional[Portfolio]
    config = Config()


class CreatePortfolio(BaseModel):
    """Create request for Portfolio."""
    nft_holder_id: str = Field(..., description="Unique identifier for the NFT holder")
    assets: List[str] = Field([], description="List of asset IDs")
    config = Config()


class UpdatePortfolio(BaseModel):
    """Update request for Portfolio."""
    nft_holder_id: str = Field(..., description="Unique identifier for the NFT holder")
    assets: List[str] = Field([], description="List of asset IDs")
    config = Config()


class ResponsePortfolio(BaseModel):
    """Response schema for Portfolio."""
    nft_holder_id: str
    assets: List[Asset]
    total_value: float
    config = Config()


class CreateRebalancingRecommendation(BaseModel):
    """Create request for RebalancingRecommendation."""
    nft_holder_id: str = Field(..., description="Unique identifier for the NFT holder")
    recommendation: str = Field(..., description="GPT-5 recommendation text")
    confidence: float = Field(0.8, description="Confidence level of the recommendation (0.0-1.0)")
    config = Config()


class UpdateRebalancingRecommendation(BaseModel):
    """Update request for RebalancingRecommendation."""
    recommendation: Optional[str] = Field(None, description="GPT-5 recommendation text")
    confidence: Optional[float] = Field(None, description="Confidence level of the recommendation (0.0-1.0)")
    config = Config()


class ResponseRebalancingRecommendation(BaseModel):
    """Response schema for RebalancingRecommendation."""
    id: str
    nft_holder_id: str
    timestamp: datetime
    recommendation: str
    confidence: float
    config = Config()