from typing import List, Optional
from pydantic import BaseModel, Field
from pydantic import ConfigDict
from datetime import datetime

class FieldValidator(BaseModel):
    """Base class for field validators."""
    pass

class NFTHolder(BaseModel):
    """Represents a Mossland NFT holder within the TerraForm system."""
    id: int = Field(..., description="Unique identifier for the NFT holder", min=1)
    name: str = Field(..., description="Holder's name")
    wallet_address: str = Field(..., description="Holder's Terra wallet address")
    created_at: datetime = Field(default=datetime.utcnow, description="Timestamp of NFT holder creation")
    
    
    model_config = ConfigDict(
        example={
            "id": 123,
            "name": "Alice Smith",
            "wallet_address": "terra1...",
            "created_at": datetime(2023, 1, 1, 12, 0, 0)
        }
    )


class Portfolio(BaseModel):
    """Represents the DeFi portfolio managed by a TerraForm agent for a specific NFT holder."""
    id: int = Field(..., description="Unique identifier for the portfolio", min=1)
    nft_holder_id: int = Field(..., description="ID of the NFT holder this portfolio belongs to")
    name: str = Field(..., description="Portfolio name")
    created_at: datetime = Field(default=datetime.utcnow, description="Timestamp of portfolio creation")
    
    model_config = ConfigDict(
        example={
            "id": 456,
            "nft_holder_id": 123,
            "name": "My Portfolio",
            "created_at": datetime(2023, 2, 15, 8, 30, 0)
        }
    )


class AssetPosition(BaseModel):
    """Represents a single asset held within a portfolio."""
    id: int = Field(..., description="Unique identifier for the asset position", min=1)
    portfolio_id: int = Field(..., description="ID of the portfolio this asset position belongs to")
    asset_type: str = Field(..., description="Type of asset (e.g., LP token, stablecoin)")
    quantity: float = Field(..., description="Quantity of the asset held", gt=0)
    
    model_config = ConfigDict(
        example={
            "id": 789,
            "portfolio_id": 456,
            "asset_type": "LP Token",
            "quantity": 10.5
        }
    )


class GPT5Recommendation(BaseModel):
    """Stores recommendations generated by the GPT-5 API for portfolio rebalancing."""
    id: int = Field(..., description="Unique identifier for the recommendation", min=1)
    portfolio_id: int = Field(..., description="ID of the portfolio this recommendation applies to")
    recommendation: str = Field(..., description="GPT-5 recommendation text")
    confidence_score: float = Field(..., description="Confidence score of the recommendation (0.0 - 1.0)", gt=0.0, lt=1.0)
    
    model_config = ConfigDict(
        example={
            "id": 101,
            "portfolio_id": 456,
            "recommendation": "Rebalance portfolio to increase exposure to LP Token.",
            "confidence_score": 0.85
        }
    )


class CreateNFTHolder(BaseModel):
    """Create request schema for NFTHolder."""
    name: str = Field(..., description="Holder's name")
    wallet_address: str = Field(..., description="Holder's Terra wallet address")

    model_config = ConfigDict(example={
        "name": "Bob Johnson",
        "wallet_address": "terra1..."
    })


class CreatePortfolio(BaseModel):
    """Create request schema for Portfolio."""
    nft_holder_id: int = Field(..., description="ID of the NFT holder this portfolio belongs to")
    name: str = Field(..., description="Portfolio name")

    model_config = ConfigDict(example={
        "nft_holder_id": 123,
        "name": "My New Portfolio"
    })


class CreateAssetPosition(BaseModel):
    """Create request schema for AssetPosition."""
    portfolio_id: int = Field(..., description="ID of the portfolio this asset position belongs to")
    asset_type: str = Field(..., description="Type of asset (e.g., LP token, stablecoin)")
    quantity: float = Field(..., description="Quantity of the asset held", gt=0)

    model_config = ConfigDict(example={
        "portfolio_id": 456,
        "asset_type": "LP Token",
        "quantity": 10.5
    })


class CreateGPT5Recommendation(BaseModel):
    """Create request schema for GPT5Recommendation."""
    portfolio_id: int = Field(..., description="ID of the portfolio this recommendation applies to")
    recommendation: str = Field(..., description="GPT-5 recommendation text")
    confidence_score: float = Field(..., description="Confidence score of the recommendation (0.0 - 1.0)", gt=0.0, lt=1.0)

    model_config = ConfigDict(example={
        "portfolio_id": 456,
        "recommendation": "Rebalance portfolio to increase exposure to LP Token.",
        "confidence_score": 0.85
    })