/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTHolder {
  id: string;
  network: string;
  walletAddress: string;
  riskProfile: string;
}

export interface Portfolio {
  id: string;
  nftHolderId: string;
  totalValue: number;
  assetAllocation: any;
}

export interface MarketData {
  id: string;
  assetSymbol: string;
  price: number;
  volume: number;
}

export interface GPT5Response {
  id: string;
  portfolioId: string;
  prompt: string;
  response: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
