/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface SmartContract {
  address: string;
  name: string;
  abi: string;
  createdAt: string;
}

export interface VulnerabilityReport {
  id: string;
  contractAddress: string;
  vulnerabilityType: string;
  severity: string;
  description: string;
  createdAt: string;
}

export interface RiskAssessment {
  contractAddress: string;
  riskScore: number;
  vulnerabilityCount: number;
  lastUpdated: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
