/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface Portfolio {
  id: string;
  userId: string;
  riskProfile: string;
  returnTarget: number;
  createdAt: string;
}

export interface Asset {
  id: string;
  assetType: string;
  quantity: number;
  assetPrice: number;
  assetDetails: any;
}

export interface ChainlinkDataFeed {
  id: string;
  assetType: string;
  data: number;
  lastUpdated: string;
}

export interface GPT5Strategy {
  id: string;
  strategyName: string;
  strategyDescription: string;
  assetAllocation: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
