/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface SmartContract {
  id: string;
  contractAddress: string;
  code: string;
  vulnerabilityScore: number;
  remediationSuggestions: any;
  createdAt: string;
}

export interface VulnerabilityReport {
  id: string;
  contractId: string;
  description: string;
  severity: string;
  remediationSuggestion: string;
  createdAt: string;
}

export interface User {
  id: string;
  username: string;
  role: string;
  createdAt: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
