from sqlalchemy import Column, String, Float, DateTime, JSON, Enum, Integer
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import back_populates
from uuid import uuid4
from enum import Enum

Base = declarative_base()

class RiskProfile(Base):
    """
    Represents the risk tolerance parameters for a portfolio.
    """
    __tablename__ = 'risk_profiles'

    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    volatilityThreshold = Column(Float, nullable=False)
    maxDrawdown = Column(Float, nullable=False)
    assetAllocation = Column(JSON, nullable=False)
    created_at = Column(DateTime, server_default=datetime.utcnow)
    updated_at = Column(DateTime, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<RiskProfile(id='{self.id}', name='{self.name}')>"

class Portfolio(Base):
    """
    Represents a user's DeFi portfolio within the Mossland ecosystem.
    """
    __tablename__ = 'portfolios'

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    nftHolderAddress = Column(String, nullable=False)
    createdAt = Column(DateTime, server_default=datetime.utcnow)
    riskTolerance = Column(String, nullable=False)
    currentAssets = Column(JSON, nullable=False)

    def __repr__(self):
        return f"<Portfolio(id='{self.id}', nftHolderAddress='{self.nftHolderAddress}')>"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if 'id' not in kwargs:
            self.id = str(uuid4())

class Strategy(Base):
    """
    Represents a dynamic DeFi portfolio rebalancing strategy generated by GPT-5.
    """
    __tablename__ = 'strategies'

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    name = Column(String, nullable=False)
    parameters = Column(JSON, nullable=False)
    SharpeRatio = Column(Float, nullable=False)
    created_at = Column(DateTime, server_default=datetime.utcnow)
    updated_at = Column(DateTime, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<Strategy(id='{self.id}', name='{self.name}')>"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if 'id' not in kwargs:
            self.id = str(uuid4())

from datetime import datetime