/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTFraction {
  tokenId: string;
  fractionId: string;
  ownerAddress: any;
  fractionPercentage: any;
}

export interface Portfolio {
  userId: any;
  createdAt: string;
}

export interface User {
  address: any;
  riskProfile: string;
}

export interface PriceFeed {
  assetAddress: any;
  price: any;
  timestamp: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
