/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface Stablecoin {
  id: string;
  name: string;
  totalSupply: any;
  decimals: any;
  riskScore: number;
}

export interface Transaction {
  id: string;
  timestamp: string;
  sender: any;
  receiver: any;
  amount: any;
  blockNumber: any;
}

export interface Validator {
  id: string;
  address: any;
  reputationScore: number;
}

export interface RiskScore {
  id: string;
  stablecoinId: string;
  score: number;
  timestamp: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
