/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface User {
  id: string;
  nft_id: string;
  createdAt: string;
}

export interface Portfolio {
  id: string;
  userId: string;
  risk_profile: string;
}

export interface Position {
  id: string;
  portfolioId: string;
  asset_id: string;
  quantity: number;
  price: number;
}

export interface AIModelData {
  id: string;
  timestamp: string;
  asset_data: Record<string, any>;
}

export interface AIModel {
  id: string;
  model_version: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
