from sqlalchemy import Column, String, DateTime, Float, Enum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import back_populates
from uuid import UUID

from datetime import datetime

Base = declarative_base()

class ClaudeOpusResponse(Base):
    """
    Represents the response generated by the Claude Opus API after analyzing a smart contract.
    """
    __tablename__ = 'claude_opus_responses'

    id = Column(UUID, primary_key=True)
    analysisResult = Column(String)
    confidenceScore = Column(Float)
    created_at = Column(DateTime, server_default=datetime.utcnow())
    updated_at = Column(DateTime, server_default=datetime.utcnow(), server_onupdate=datetime.utcnow())

    def __repr__(self):
        return f"<ClaudeOpusResponse(id={self.id}, analysisResult='{self.analysisResult}', confidenceScore={self.confidenceScore})>"

class NFTWithdrawalTransaction(Base):
    """
    A record of an NFT withdrawal transaction on the blockchain.
    """
    __tablename__ = 'nft_withdrawal_transactions'

    id = Column(UUID, primary_key=True)
    nftAddress = Column(String)
    senderAddress = Column(String)
    timestamp = Column(DateTime)
    status = Column(String)
    created_at = Column(DateTime, server_default=datetime.utcnow())
    updated_at = Column(DateTime, server_default=datetime.utcnow(), server_onupdate=datetime.utcnow())

    def __repr__(self):
        return f"<NFTWithdrawalTransaction(id={self.id}, nftAddress='{self.nftAddress}', senderAddress='{self.senderAddress}', timestamp={self.timestamp}, status='{self.status}')>"

    back_populates = 'MosslandNFTHolder'

class MosslandNFTHolder(Base):
    """
    Represents a holder of Mossland NFTs.
    """
    __tablename__ = 'mossland_nft_holders'

    id = Column(UUID, primary_key=True)
    address = Column(String)
    name = Column(String)
    created_at = Column(DateTime, server_default=datetime.utcnow())
    updated_at = Column(DateTime, server_default=datetime.utcnow(), server_onupdate=datetime.utcnow())

    def __repr__(self):
        return f"<MosslandNFTHolder(id={self.id}, address='{self.address}', name='{self.name}')>"