from pydantic import BaseModel, Field
from typing import Optional

class BaseNFTTransaction(BaseModel):
    id: str = Field(..., description="Unique identifier for the transaction")
    timestamp: str = Field(..., description="Timestamp of the transaction in ISO 8601 format")
    blockchain: str = Field(..., description="Blockchain network where the transaction occurred")
    status: str = Field(..., description="Status of the transaction (e.g., 'pending', 'success', 'failed')")

    class Config:
        schema_extra = {
            "example": {
                "id": "0x1234567890abcdef1234567890abcdef",
                "timestamp": "2023-10-27T10:00:00Z",
                "blockchain": "Ethereum",
                "status": "success"
            }
        }


class CreateNFTTransaction(BaseNFTTransaction):
    nft_id: str = Field(..., description="ID of the NFT withdrawn")
    sender_address: str = Field(..., description="Address of the sender")
    recipient_address: str = Field(..., description="Address of the recipient")

    class Config:
        schema_extra = {
            "example": {
                "id": "0x1234567890abcdef1234567890abcdef",
                "timestamp": "2023-10-27T10:00:00Z",
                "blockchain": "Ethereum",
                "status": "success",
                "nft_id": "0x6789abcdef0123456789abcdef01",
                "sender_address": "0x1234567890abcdef1234567890",
                "recipient_address": "0xdef0123456789abcdef012345678"
            }
        }


class UpdateNFTTransaction(BaseNFTTransaction):
    nft_id: Optional[str] = Field(None, description="ID of the NFT withdrawn (optional for updates)")
    sender_address: Optional[str] = Field(None, description="Address of the sender (optional for updates)")
    recipient_address: Optional[str] = Field(None, description="Address of the recipient (optional for updates)")

    class Config:
        schema_extra = {
            "example": {
                "id": "0x1234567890abcdef1234567890abcdef",
                "timestamp": "2023-10-27T10:00:00Z",
                "blockchain": "Ethereum",
                "status": "pending",
                "nft_id": "0x6789abcdef0123456789abcdef01",
                "sender_address": "0x1234567890abcdef1234567890",
                "recipient_address": "0xdef0123456789abcdef012345678"
            }
        }


class ResponseNFTTransaction(BaseNFTTransaction):
    transaction_details: dict = Field(..., description="Detailed information about the transaction")

    class Config:
        schema_extra = {
            "example": {
                "id": "0x1234567890abcdef1234567890abcdef",
                "timestamp": "2023-10-27T10:00:00Z",
                "blockchain": "Ethereum",
                "status": "success",
                "transaction_details": {
                    "block_hash": "0xabcdef1234567890abcdef1234567890",
                    "gas_used": 1000,
                    "input_data": "0x...",
                    "output_data": "0x..."
                }
            }
        }


class MosslandNFTHolder(BaseModel):
    wallet_address: str = Field(..., description="Wallet address of the holder")
    nft_count: int = Field(..., description="Number of Mossland NFTs held")
    nft_ids: list[str] = Field(..., description="List of NFT IDs held")

    class Config:
        schema_extra = {
            "example": {
                "wallet_address": "0x1234567890abcdef1234567890",
                "nft_count": 5,
                "nft_ids": ["0x6789abcdef0123456789abcdef01", "0x6789abcdef0123456789abcdef02", "0x6789abcdef0123456789abcdef03", "0x6789abcdef0123456789abcdef04", "0x6789abcdef0123456789abcdef05"]
            }
        }


class ClaudeOpusResponse(BaseModel):
    response_id: str = Field(..., description="Unique identifier for the response")
    timestamp: str = Field(..., description="Timestamp of the response generation")
    smart_contract_address: str = Field(..., description="Address of the smart contract analyzed")
    analysis_result: str = Field(..., description="The analysis result generated by Claude Opus")
    confidence_score: float = Field(..., description="Confidence score of the analysis result (0.0 - 1.0)")

    class Config:
        schema_extra = {
            "example": {
                "response_id": "0x1234567890abcdef1234567890abcdef",
                "timestamp": "2023-10-27T10:00:00Z",
                "smart_contract_address": "0x1234567890abcdef1234567890",
                "analysis_result": "The smart contract is likely to be malicious.",
                "confidence_score": 0.85
            }
        }