/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFT {
  tokenId: string;
  metadata: any;
  valuation: any;
}

export interface PortfolioHolding {
  userId: string;
  tokenId: string;
  quantity: number;
  valuation: any;
}

export interface User {
  userId: string;
  portfolio: any;
}

export interface RiskAssessment {
  tokenId: string;
  riskScore: any;
  alertThreshold: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
