/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTHolder {
  id: string;
  nftAddress: string;
  createdAt: string;
}

export interface PortfolioPosition {
  id: string;
  nftHolderId: string;
  assetAddress: string;
  quantity: number;
  lastUpdated: string;
}

export interface RiskParameter {
  id: string;
  riskTolerance: number;
  timeHorizon: number;
}

export interface PerformanceData {
  id: string;
  portfolioPositionId: string;
  timestamp: string;
  price: number;
  quantity: number;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
