from sqlalchemy import Column, Integer, String, Float, DateTime, JSON, UUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import back_populates, relationship

Base = declarative_base()

class User(Base):
    """Represents a user interacting with the system."""
    __tablename__ = 'user'

    id = Column(UUID, primary_key=True)
    userId = Column(String, unique=True, nullable=False)
    address = Column(String, nullable=False)
    created_at = Column(DateTime, server_default=DateTime.utcnow)
    updated_at = Column(DateTime, onupdate=DateTime.utcnow)

    def __repr__(self):
        return f"<User(userId='{self.userId}', address='{self.address}')>"

class NFT(Base):
    """Represents a Mossland NFT asset."""
    __tablename__ = 'nft'

    id = Column(UUID, primary_key=True)
    tokenId = Column(String, nullable=False)
    metadata = Column(JSON, nullable=False)
    owner = Column(String, nullable=False)
    created_at = Column(DateTime, server_default=DateTime.utcnow)
    updated_at = Column(DateTime, onupdate=DateTime.utcnow)

    def __repr__(self):
        return f"<NFT(tokenId='{self.tokenId}', owner='{self.owner}')>"

    # Relationship: NFT belongs to User
    user = relationship("User", back_populates="nft")

class Portfolio(Base):
    """Represents a user's NFT portfolio within the system."""
    __tablename__ = 'portfolio'

    id = Column(UUID, primary_key=True)
    userId = Column(String, nullable=False)
    totalValue = Column(Float, nullable=False)
    lastUpdated = Column(DateTime, nullable=False)
    created_at = Column(DateTime, server_default=DateTime.utcnow)
    updated_at = Column(DateTime, onupdate=DateTime.utcnow)

    def __repr__(self):
        return f"<Portfolio(userId='{self.userId}', totalValue={self.totalValue})>"

    # Relationship: Portfolio belongs to User
    user = relationship("User", back_populates="portfolio")

class MarketData(Base):
    """Represents market data fetched from external sources."""
    __tablename__ = 'market_data'

    id = Column(UUID, primary_key=True)
    timestamp = Column(DateTime, nullable=False)
    asset = Column(String, nullable=False)
    price = Column(Float, nullable=False)
    created_at = Column(DateTime, server_default=DateTime.utcnow)
    updated_at = Column(DateTime, onupdate=DateTime.utcnow)

    def __repr__(self):
        return f"<MarketData(timestamp='{self.timestamp}', asset='{self.asset}', price={self.price})>"

class RebalanceStrategy(Base):
    """Represents a portfolio rebalancing strategy generated by GPT-5."""
    __tablename__ = 'rebalance_strategy'

    id = Column(UUID, primary_key=True)
    strategyId = Column(String, nullable=False)
    description = Column(String, nullable=False)
    created_at = Column(DateTime, server_default=DateTime.utcnow)
    updated_at = Column(DateTime, onupdate=DateTime.utcnow)

    def __repr__(self):
        return f"<RebalanceStrategy(strategyId='{self.strategyId}', description='{self.description}')>"

if __name__ == '__main__':
    # Example usage (not for actual database interaction)
    Base.metadata.create_all(bind=None)  # Create the tables
    user1 = User(userId="user123", address="0xabc...")
    nft1 = NFT(tokenId="nft456", metadata={"name": "Mossland NFT", "symbol": "MSL"}, owner=user1.userId)
    portfolio1 = Portfolio(userId=user1.userId, totalValue=100.0, lastUpdated=DateTime.utcnow())

    print(user1)
    print(nft1)
    print(portfolio1)