from sqlalchemy import Column, Integer, String, Float, DateTime, JSON, UUID
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import back_populates, relationship

Base = declarative_base()

class NFT(Base):
    """
    Represents a Mossland NFT asset.
    """
    __tablename__ = 'nft'

    id = Column(UUID, primary_key=True)
    tokenId = Column(String, unique=True, nullable=False)
    owner = Column(String, nullable=False)
    metadata = Column(JSON, nullable=True)
    value = Column(Float, nullable=True)

    __repr__ = lambda self: f"NFT(tokenId='{self.tokenId}', owner='{self.owner}', value={self.value})"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if self.id is None:
            self.id = UUID.generate()
        if self.created_at is None:
            self.created_at = datetime.utcnow()
        if self.updated_at is None:
            self.updated_at = datetime.utcnow()


class Portfolio(Base):
    """
    Represents a user's NFT portfolio.
    """
    __tablename__ = 'portfolio'

    id = Column(UUID, primary_key=True)
    portfolioId = Column(String, unique=True, nullable=False)
    userId = Column(String, nullable=False)
    holdings = Column(String, nullable=False)

    __repr__ = lambda self: f"Portfolio(portfolioId='{self.portfolioId}', userId='{self.userId}', holdings={self.holdings})"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if self.id is None:
            self.id = UUID.generate()
        if self.created_at is None:
            self.created_at = datetime.utcnow()
        if self.updated_at is None:
            self.updated_at = datetime.utcnow()

    holdings_array = relationship(
        "NFT",
        collection="holdings",
        back_populates="portfolio"
    )


class MarketData(Base):
    """
    Represents real-time market data for NFTs.
    """
    __tablename__ = 'market_data'

    id = Column(UUID, primary_key=True)
    tokenId = Column(String, nullable=False)
    price = Column(Float, nullable=False)
    volume = Column(Float, nullable=False)
    timestamp = Column(DateTime, nullable=False)

    __repr__ = lambda self: f"MarketData(tokenId='{self.tokenId}', price={self.price}, volume={self.volume}, timestamp={self.timestamp})"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if self.id is None:
            self.id = UUID.generate()
        if self.created_at is None:
            self.created_at = datetime.utcnow()
        if self.updated_at is None:
            self.updated_at = datetime.utcnow()

    nft = relationship(
        "NFT",
        back_populates="market_data"
    )


class GPT5Prediction(Base):
    """
    Represents a prediction generated by the GPT-5 oracle.
    """
    __tablename__ = 'gpt5_prediction'

    id = Column(UUID, primary_key=True)
    tokenId = Column(String, nullable=False)
    predictedValue = Column(Float, nullable=False)
    confidenceInterval = Column(Float, nullable=False)
    timestamp = Column(DateTime, nullable=False)

    __repr__ = lambda self: f"GPT5Prediction(tokenId='{self.tokenId}', predictedValue={self.predictedValue}, confidenceInterval={self.confidenceInterval}, timestamp={self.timestamp})"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if self.id is None:
            self.id = UUID.generate()
        if self.created_at is None:
            self.created_at = datetime.utcnow()
        if self.updated_at is None:
            self.updated_at = datetime.utcnow()

    nft = relationship(
        "NFT",
        back_populates="gpt5_predictions"
    )

from datetime import datetime