from sqlalchemy import Column, Integer, String, DateTime, Float, JSON, Enum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import back_populates
from uuid import uuid4
import datetime

Base = declarative_base()

class User(Base):
    """Represents a MOC holder using the system."""
    __tablename__ = 'user'
    id = Column(String, primary_key=True)
    riskTolerance = Column(String)
    mocHolding = Column(Float)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    def __repr__(self):
        return f"<User(id='{self.id}', riskTolerance='{self.riskTolerance}', mocHolding={self.mocHolding})>"


class Portfolio(Base):
    """Represents a user's DeFi portfolio."""
    __tablename__ = 'portfolio'
    id = Column(String, primary_key=True)
    userId = Column(String, ForeignKey('user.id'))
    holdings = Column(JSON)
    riskProfile = Column(String)
    lastRebalance = Column(DateTime)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    def __repr__(self):
        return f"<Portfolio(id='{self.id}', userId='{self.userId}', riskProfile='{self.riskProfile}')>"

    back_populates = 'User'


class Asset(Base):
    """Represents a DeFi asset within a portfolio."""
    __tablename__ = 'asset'
    id = Column(String, primary_key=True)
    name = Column(String)
    symbol = Column(String)
    price = Column(Float)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    def __repr__(self):
        return f"<Asset(id='{self.id}', name='{self.name}', symbol='{self.symbol}', price={self.price})>"


class RebalanceRationale(Base):
    """Stores the explanation generated by ChatGPT for a rebalancing decision."""
    __tablename__ = 'rebalance_rationale'
    id = Column(String, primary_key=True)
    portfolioId = Column(String, ForeignKey('portfolio.id'))
    rationaleText = Column(String)
    timestamp = Column(DateTime)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    def __repr__(self):
        return f"<RebalanceRationale(id='{self.id}', portfolioId='{self.portfolioId}', rationaleText='{self.rationaleText}')>"

    back_populates = 'Portfolio'


if __name__ == '__main__':
    from sqlalchemy import create_engine
    engine = create_engine('sqlite:///:memory:')
    Base.metadata.create_all(bind=engine)