from typing import Optional
from pydantic import BaseModel, Field
from pydantic import ConfigDict
from datetime import datetime

class FieldValidator(BaseModel):
    """
    Base class for field validators.
    """
    pass

class NFT(BaseModel):
    """
    Represents a Mossland NFT asset.
    """
    id: str = Field(..., description="Unique NFT identifier", min_length=36)
    name: str = Field(..., description="NFT name")
    description: Optional[str] = Field(None, description="NFT description")
    image_url: str = Field(..., description="URL to the NFT image")
    metadata: ConfigDict = Field(default_factory=ConfigDict, description="NFT metadata")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="NFT creation timestamp")
    
    schema_config = ConfigDict(
        extra=None,
        populate_by_name=True,
        arbitrary_types=True,
    )

    example = {
        "id": "0x1234567890abcdef1234567890abcdef12345678",
        "name": "Mossland Plot 1",
        "description": "A beautiful plot in the Mossland",
        "image_url": "https://example.com/mossland_plot_1.png",
        "metadata": {
            "location": "Sector A, Block 2",
            "size": 100,
            "terrain": "Grassland"
        },
        "created_at": datetime.utcnow()
    }


class Portfolio(BaseModel):
    """
    Represents a user's NFT portfolio.
    """
    user_id: str = Field(..., description="User identifier")
    nfts: list[NFT] = Field([], description="List of NFTs in the portfolio")
    
    schema_config = ConfigDict(
        extra=None,
        populate_by_name=True,
        arbitrary_types=True,
    )

    example = {
        "user_id": "user123",
        "nfts": [
            NFT(id="0x1234567890abcdef1234567890abcdef12345678", name="Mossland Plot 1"),
            NFT(id="0xabcdef1234567890abcdef1234567890abcdef12345678", name="Mossland Plot 2")
        ]
    }


class MarketData(BaseModel):
    """
    Represents real-time market data for NFTs.
    """
    nft_id: str = Field(..., description="NFT identifier")
    price: float = Field(..., description="Current price")
    volume: float = Field(..., description="Trading volume")
    
    schema_config = ConfigDict(
        extra=None,
        populate_by_name=True,
        arbitrary_types=True,
    )

    example = {
        "nft_id": "0x1234567890abcdef1234567890abcdef12345678",
        "price": 100.0,
        "volume": 10.0
    }


class GPT5Prediction(BaseModel):
    """
    Represents a prediction generated by the GPT-5 oracle.
    """
    nft_id: str = Field(..., description="NFT identifier")
    prediction: str = Field(..., description="Prediction text")
    confidence: float = Field(..., description="Prediction confidence level")
    
    schema_config = ConfigDict(
        extra=None,
        populate_by_name=True,
        arbitrary_types=True,
    )

    example = {
        "nft_id": "0xabcdef1234567890abcdef1234567890abcdef12345678",
        "prediction": "The price will increase",
        "confidence": 0.8
    }