from typing import Optional
from pydantic import BaseModel, Field
from pydantic import ConfigDict
from datetime import datetime

class FieldValidator(BaseModel):
    """
    Base class for field validators.
    """
    pass

class RebalanceRationale(BaseModel):
    """
    Stores the explanation generated by ChatGPT for a rebalancing decision.
    """
    explanation: str = Field(..., description="ChatGPT generated explanation for the rebalancing decision.")
    timestamp: datetime = Field(default=datetime.now, description="Timestamp of when the rationale was generated.")

    @classmethod
    def from_dict(cls, data):
        return cls(explanation=data['explanation'], timestamp=data['timestamp'])

    @classmethod
    def from_json(cls, json):
        return cls.from_dict(json)

    @classmethod
    def from_dict_like(cls, data):
        return cls(explanation=data.explanation, timestamp=data.timestamp)

    @classmethod
    def from_json_like(cls, json):
        return cls.from_dict_like(json)


class Asset(BaseModel):
    """
    Represents a DeFi asset within a portfolio.
    """
    id: str = Field(..., description="Unique identifier for the asset.")
    name: str = Field(..., description="Name of the asset (e.g., USDT, ETH).")
    symbol: str = Field(..., description="Symbol of the asset (e.g., USDT, ETH).")
    quantity: float = Field(..., description="Quantity of the asset held.")
    decimals: int = Field(..., description="Number of decimal places for the asset.")
    blockchain: str = Field(..., description="Blockchain the asset is on (e.g., Ethereum, Binance Smart Chain).")

    class Config:
        schema_extra = {
            "example": {
                "id": "asset123",
                "name": "USDT",
                "symbol": "USDT",
                "quantity": 100.0,
                "decimals": 6,
                "blockchain": "Ethereum"
            }
        }


class Portfolio(BaseModel):
    """
    Represents a user's DeFi portfolio.
    """
    id: str = Field(..., description="Unique identifier for the portfolio.")
    user_id: str = Field(..., description="Unique identifier for the user owning the portfolio.")
    name: Optional[str] = Field(None, description="Name of the portfolio (optional).")
    assets: list[Asset] = Field([], description="List of assets in the portfolio.")

    class Config:
        schema_extra = {
            "example": {
                "id": "portfolio456",
                "user_id": "user789",
                "assets": [
                    {
                        "id": "asset123",
                        "name": "USDT",
                        "symbol": "USDT",
                        "quantity": 100.0,
                        "decimals": 6,
                        "blockchain": "Ethereum"
                    }
                ]
            }
        }


class User(BaseModel):
    """
    Represents a MOC holder using the system.
    """
    id: str = Field(..., description="Unique identifier for the user.")
    username: str = Field(..., description="User's username.")
    email: str = Field(..., description="User's email address.")
    created_at: datetime = Field(default=datetime.now, description="Timestamp of user creation.")

    class Config:
        schema_extra = {
            "example": {
                "id": "user789",
                "username": "john.doe",
                "email": "john.doe@example.com",
                "created_at": datetime.now()
            }
        }


class CreateUserSchema(BaseModel):
    """
    Create User Request Schema
    """
    username: str = Field(..., description="User's username.")
    email: str = Field(..., description="User's email address.")

    class Config:
        schema_extra = {
            "example": {
                "username": "newuser",
                "email": "newuser@example.com"
            }
        }


class UpdateUserSchema(BaseModel):
    """
    Update User Request Schema
    """
    username: Optional[str] = Field(None, description="User's username (optional).")
    email: Optional[str] = Field(None, description="User's email address (optional).")

    class Config:
        schema_extra = {
            "example": {
                "username": "updateduser",
                "email": "updateduser@example.com"
            }
        }


class CreatePortfolioSchema(BaseModel):
    """
    Create Portfolio Request Schema
    """
    user_id: str = Field(..., description="Unique identifier for the user owning the portfolio.")
    name: Optional[str] = Field(None, description="Name of the portfolio (optional).")

    class Config:
        schema_extra = {
            "example": {
                "user_id": "user789",
                "name": "My Portfolio"
            }
        }


class UpdatePortfolioSchema(BaseModel):
    """
    Update Portfolio Request Schema
    """
    name: Optional[str] = Field(None, description="Name of the portfolio (optional).")

    class Config:
        schema_extra = {
            "example": {
                "name": "Updated Portfolio Name"
            }
        }

class CreateAssetSchema(BaseModel):
    """
    Create Asset Request Schema
    """
    name: str = Field(..., description="Name of the asset (e.g., USDT, ETH).")
    symbol: str = Field(..., description="Symbol of the asset (e.g., USDT, ETH).")
    quantity: float = Field(..., description="Quantity of the asset held.")
    decimals: int = Field(..., description="Number of decimal places for the asset.")
    blockchain: str = Field(..., description="Blockchain the asset is on (e.g., Ethereum, Binance Smart Chain).")

    class Config:
        schema_extra = {
            "example": {
                "name": "USDT",
                "symbol": "USDT",
                "quantity": 100.0,
                "decimals": 6,
                "blockchain": "Ethereum"
            }
        }

class ResponseUserSchema(BaseModel):
    """
    Response User Schema
    """
    id: str
    username: str
    email: str
    created_at: datetime

    class Config:
        schema_extra = {
            "example": {
                "id": "user789",
                "username": "john.doe",
                "email": "john.doe@example.com",
                "created_at": datetime.now()
            }
        }

class ResponsePortfolioSchema(BaseModel):
    """
    Response Portfolio Schema
    """
    id: str
    user_id: str
    name: Optional[str]
    assets: list[Asset]

    class Config:
        schema_extra = {
            "example": {
                "id": "portfolio456",
                "user_id": "user789",
                "name": "My Portfolio",
                "assets": [
                    {
                        "id": "asset123",
                        "name": "USDT",
                        "symbol": "USDT",
                        "quantity": 100.0,
                        "decimals": 6,
                        "blockchain": "Ethereum"
                    }
                ]
            }
        }

class ResponseAssetSchema(BaseModel):
    """
    Response Asset Schema
    """
    id: str
    name: str
    symbol: str
    quantity: float
    decimals: int
    blockchain: str

    class Config:
        schema_extra = {
            "example": {
                "id": "asset123",
                "name": "USDT",
                "symbol": "USDT",
                "quantity": 100.0,
                "decimals": 6,
                "blockchain": "Ethereum"
            }
        }

class ResponseRebalanceRationaleSchema(BaseModel):
    """
    Response Rebalance Rationale Schema
    """
    explanation: str
    timestamp: datetime

    class Config:
        schema_extra = {
            "example": {
                "explanation": "ChatGPT generated explanation for the rebalancing decision.",
                "timestamp": datetime.now()
            }
        }