/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface RWA Portfolio {
  id: string;
  nftHolderId: string;
  riskTolerance: string;
  createdAt: string;
}

export interface RWA Asset {
  id: string;
  assetName: string;
  assetPrice: number;
  assetQuantity: number;
  createdAt: string;
}

export interface GPT-5 Agent {
  id: string;
  lastRunTime: string;
  prompt: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
