/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface SecurityToken {
  id: string;
  ticker: string;
  name: string;
  price: number;
  quantity: number;
  createdAt: string;
}

export interface PortfolioPosition {
  id: string;
  userId: string;
  securityTokenId: string;
  quantity: number;
  entryPrice: number;
  createdAt: string;
}

export interface RebalancingRecommendation {
  id: string;
  userId: string;
  securityTokenId: string;
  newQuantity: number;
  reason: string;
  timestamp: string;
}

export interface User {
  id: string;
  username: string;
  riskTolerance: number;
  createdAt: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
