/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface ENS Domain {
  id: string;
  name: string;
  tokenId: string;
  owner: any;
}

export interface NFT {
  id: string;
  tokenId: string;
  metadata: any;
  domainId: string;
}

export interface User {
  id: string;
  address: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
