/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface User {
  id: string;
  riskTolerance: string;
  mocHolding: any;
}

export interface Portfolio {
  id: string;
  userId: string;
  holdings: any;
  riskProfile: string;
  lastRebalance: string;
}

export interface Asset {
  id: string;
  name: string;
  symbol: string;
  price: any;
}

export interface RebalanceRationale {
  id: string;
  portfolioId: string;
  rationaleText: string;
  timestamp: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
