/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFT {
  tokenId: string;
  metadata: any;
  owner: any;
}

export interface User {
  userId: string;
  address: any;
}

export interface Portfolio {
  userId: string;
  totalValue: number;
  lastUpdated: string;
}

export interface MarketData {
  timestamp: string;
  asset: string;
  price: number;
}

export interface RebalanceStrategy {
  strategyId: string;
  description: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
