/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFT {
  tokenId: string;
  owner: any;
  metadata: Record<string, any>;
  quantity: any;
}

export interface Portfolio {
  portfolioId: string;
  userId: any;
  holdings: Record<string, any>;
}

export interface MarketData {
  tokenId: string;
  price: number;
  volume: any;
  timestamp: string;
}

export interface Prediction {
  tokenId: string;
  predictedValue: number;
  confidenceInterval: number;
  timestamp: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
