/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFT Withdrawal Transaction {
  id: string;
  nftAddress: string;
  senderAddress: string;
  timestamp: string;
  status: string;
}

export interface Mossland NFT Holder {
  address: string;
  name: string;
}

export interface Claude Opus Response {
  analysisResult: string;
  confidenceScore: number;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
