/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface SmartContract {
  address: string;
  name: string;
  codeHash: string;
  compilerVersion: string;
}

export interface Transaction {
  hash: string;
  blockNumber: number;
  timestamp: string;
  from: string;
  to: string;
  value: number;
}

export interface VulnerabilityPrediction {
  id: string;
  contractAddress: string;
  predictedVulnerability: string;
  confidenceScore: number;
  severity: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
