/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface SmartContract {
  id: string;
  contractAddress: string;
  codeHash: string;
  createdAt: string;
}

export interface Transaction {
  id: string;
  transactionHash: string;
  timestamp: string;
  contractAddress: string;
  blockNumber: number;
}

export interface RiskScore {
  id: string;
  contractAddress: string;
  score: number;
  confidenceLevel: number;
  createdAt: string;
}

export interface User {
  id: string;
  username: string;
  dailyActiveUsers: number;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
