/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface Portfolio {
  id: string;
  userId: string;
  riskTolerance: any;
  createdAt: string;
}

export interface Transaction {
  id: string;
  portfolioId: string;
  timestamp: string;
  asset: string;
  quantity: any;
  price: any;
}

export interface RaveBlockchainData {
  id: string;
  timestamp: string;
  event: string;
  data: Record<string, any>;
}

export interface MarketIndicator {
  id: string;
  timestamp: string;
  indicatorType: string;
  value: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
