from typing import Dict, Any
from decimal import Decimal, ROUND_HALF_UP
from web3 import Web3

class RevenueRouter:
    """Routes and splits revenue generated by GPT-5 Agent SDK operations for DAO/DeFi teams."""
    
    def __init__(self, w3: Web3, config: Dict[str, Any]):
        self.w3 = w3
        self.platform_fee_bps = config.get('platform_fee_bps', 1000)
        self.agent_ops_fee_bps = config.get('agent_ops_fee_bps', 1000)
        self.treasury_fee_bps = 10000 - self.platform_fee_bps - self.agent_ops_fee_bps
        
    def calculate_splits(self, total_revenue_wei: int) -> Dict[str, int]:
        total = Decimal(total_revenue_wei)
        platform_share = int((total * self.platform_fee_bps / 10000).quantize(Decimal('1'), rounding=ROUND_HALF_UP))
        agent_share = int((total * self.agent_ops_fee_bps / 10000).quantize(Decimal('1'), rounding=ROUND_HALF_UP))
        treasury_share = total_revenue_wei - platform_share - agent_share
        
        return {
            'platform': platform_share,
            'agent_ops': agent_share,
            'treasury': treasury_share
        }

    async def distribute(self, total_revenue_wei: int, addresses: Dict[str, str], tx_options: Dict[str, Any] = None):
        splits = self.calculate_splits(total_revenue_wei)
        txs = []
        
        for role, amount in splits.items():
            if amount > 0 and addresses.get(role):
                tx = self.w3.eth.send_transaction({
                    'to': addresses[role],
                    'value': amount,
                    **(tx_options or {})
                })
                txs.append(tx)
                
        return txs