/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface DAOStrategy {
  id: string;
  name: string;
  parameters: any;
  createdAt: string;
}

export interface SimulationResult {
  id: string;
  strategyId: string;
  timestamp: string;
  outcome: any;
}

export interface AgentState {
  id: string;
  strategyId: string;
  parameters: any;
  lastSimulationResultId: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
