from typing import List, Optional
from pydantic import BaseModel, Field
from pydantic import ConfigDict
from pydantic.validator import validator

class FieldConfig(ConfigDict):
    """
    Config class for Pydantic fields.
    """
    extra = False
    yaml = False

class BaseNFT(BaseModel):
    id: Optional[int] = Field(None, description="Unique identifier for the NFT", config=FieldConfig)
    name: str = Field("Default Name", description="Name of the NFT", config=FieldConfig)
    symbol: Optional[str] = Field(None, description="Symbol of the NFT", config=FieldConfig)
    image_url: str = Field("Default Image URL", description="URL of the NFT image", config=FieldConfig)


class NFTCollection(BaseNFT):
    collection_name: str = Field("Default Collection", description="Name of the NFT collection", config=FieldConfig)
    contract_address: str = Field("Default Contract Address", description="Contract address of the NFT collection", config=FieldConfig)
    total_supply: int = Field(0, description="Total supply of the NFT collection", config=FieldConfig)
    created_at: Optional[str] = Field(None, description="Timestamp of collection creation", config=FieldConfig)
    
    
class CreateNFTCollection(NFTCollection):
    pass

class UpdateNFTCollection(NFTCollection):
    pass

class NFTCollectionResponse(NFTCollection):
    pass


class BaseNFTTransaction(BaseNFT):
    transaction_type: str = Field("Buy", description="Type of transaction (Buy, Sell, Mint)", config=FieldConfig)
    quantity: int = Field(1, description="Quantity of NFTs involved in the transaction", config=FieldConfig)
    price: Optional[float] = Field(None, description="Price per NFT", config=FieldConfig)
    timestamp: str = Field("Default Timestamp", description="Timestamp of the transaction", config=FieldConfig)


class NFTTransaction(BaseNFTTransaction):
    portfolio_id: int = Field(description="ID of the portfolio this transaction belongs to", config=FieldConfig)


class CreateNFTTransaction(NFTTransaction):
    pass

class UpdateNFTTransaction(NFTTransaction):
    pass

class NFTTransactionResponse(NFTTransaction):
    pass


class BasePortfolio(BaseNFT):
    user_id: int = Field(description="ID of the user owning the portfolio", config=FieldConfig)
    
    
class Portfolio(BasePortfolio):
    portfolio_name: str = Field("Default Portfolio", description="Name of the portfolio", config=FieldConfig)
    created_at: Optional[str] = Field(None, description="Timestamp of portfolio creation", config=FieldConfig)
    
    
class CreatePortfolio(Portfolio):
    pass

class UpdatePortfolio(Portfolio):
    pass

class PortfolioResponse(Portfolio):
    pass


class BaseRiskAssessment(BaseNFT):
    gpt5_assessment: str = Field("Default Assessment", description="Risk assessment generated by GPT-5", config=FieldConfig)
    
    
class RiskAssessment(BaseRiskAssessment):
    
    
class CreateRiskAssessment(RiskAssessment):
    pass

class UpdateRiskAssessment(RiskAssessment):
    pass

class RiskAssessmentResponse(RiskAssessment):
    pass