from sqlalchemy import Column, String, Float, Integer, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import back_populates
from uuid import uuid4
from datetime import datetime

Base = declarative_base()

class RiskAssessment(Base):
    """
    Represents the risk assessment data generated by GPT-5.
    """
    __tablename__ = 'risk_assessment'

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    portfolioId = Column(String, ForeignKey('portfolio.id'))
    gpt5Output = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<RiskAssessment(id='{self.id}', portfolioId='{self.portfolioId}', gpt5Output='{self.gpt5Output}')>"

    back_populates = {'portfolioId': 'portfolio'}


class NFTCollection(Base):
    """
    Represents a specific NFT collection for portfolio management.
    """
    __tablename__ = 'nft_collection'

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    name = Column(String, nullable=False)
    contractAddress = Column(String, nullable=False)
    tokenId = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<NFTCollection(id='{self.id}', name='{self.name}', contractAddress='{self.contractAddress}', tokenId='{self.tokenId}')>"


class Portfolio(Base):
    """
    Represents a user's NFT portfolio.
    """
    __tablename__ = 'portfolio'

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    userId = Column(String, nullable=False)
    totalValue = Column(Float, default=0.0)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<Portfolio(id='{self.id}', userId='{self.userId}', totalValue={self.totalValue})>"


class NFTTransaction(Base):
    """
    Represents a transaction involving an NFT within a portfolio.
    """
    __tablename__ = 'nft_transaction'

    id = Column(String, primary_key=True, default=lambda: str(uuid4()))
    portfolioId = Column(String, ForeignKey('portfolio.id'))
    nftCollectionId = Column(String, ForeignKey('nft_collection.id'))
    quantity = Column(Integer, nullable=False)
    transactionTimestamp = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<NFTTransaction(id='{self.id}', portfolioId='{self.portfolioId}', nftCollectionId='{self.nftCollectionId}', quantity={self.quantity}, transactionTimestamp={self.transactionTimestamp})>"

    back_populates = {'portfolioId': 'portfolio', 'nftCollectionId': 'nft_collection'}