from typing import Optional
from pydantic import BaseModel, Field
from pydantic import ConfigDict
from datetime import datetime

class FieldValidator(BaseModel):
    """Base class for field validators."""
    value: any
    
    @classmethod
    def validate(cls, value):
        """Validate the value against the field's constraints."""
        try:
            cls.update(value)
            return value
        except Exception as e:
            raise ValueError(f"Invalid value: {value}.  Error: {e}")


class Config:
    """Pydantic config class."""
    json_encoders = {
        datetime: lambda v: v.iso8601()
    }

class RiskAssessment(BaseModel):
    """Stores the risk assessment data generated by GPT-5."""
    id: int = Field(default=lambda: 1, description="Unique identifier for the risk assessment")
    timestamp: datetime = Field(default=datetime.now, description="Timestamp of the risk assessment")
    risk_score: float = Field(ge=0.0, le=1.0, description="Risk score (0.0 - 1.0)")
    assessment_details: str = Field(description="Detailed risk assessment report from GPT-5")
    model_version: str = "GPT-5"
    
    
    @classmethod
    def from_dict(cls, data):
        return cls(
            id=data.get("id", None),
            timestamp=data.get("timestamp", None),
            risk_score=data.get("risk_score", None),
            assessment_details=data.get("assessment_details", None),
            model_version=data.get("model_version", None)
        )

    
    
class NFTTransaction(BaseModel):
    """Represents a transaction involving an NFT within a portfolio."""
    id: int = Field(default=lambda: 1, description="Unique identifier for the transaction")
    timestamp: datetime = Field(default=datetime.now, description="Timestamp of the transaction")
    nft_id: int = Field(description="ID of the NFT involved in the transaction")
    portfolio_id: int = Field(description="ID of the portfolio the NFT belongs to")
    transaction_type: str = Field(
        choices=["buy", "sell", "transfer", "mint"], description="Type of transaction"
    )
    amount: float = Field(ge=0.0, description="Amount of NFT involved in the transaction")
    price: float = Field(ge=0.0, description="Price at which the transaction occurred")
    
    
    
class RiskAssessmentResponse(BaseModel):
    """Response schema for RiskAssessment."""
    id: int
    timestamp: datetime
    risk_score: float
    assessment_details: str
    model_version: str

    class Config:
        schema_extra = {
            "example": {
                "id": 1,
                "timestamp": datetime(2023, 10, 26, 10, 0, 0),
                "risk_score": 0.75,
                "assessment_details": "High risk due to market volatility.",
                "model_version": "GPT-5"
            }
        }

class NFTTransactionResponse(BaseModel):
    """Response schema for NFTTransaction."""
    id: int
    timestamp: datetime
    nft_id: int
    portfolio_id: int
    transaction_type: str
    amount: float
    price: float

    class Config:
        schema_extra = {
            "example": {
                "id": 1,
                "timestamp": datetime(2023, 10, 26, 10, 15, 0),
                "nft_id": 123,
                "portfolio_id": 456,
                "transaction_type": "buy",
                "amount": 0.5,
                "price": 100.0
            }
        }

class NFTCollectionCreate(BaseModel):
    """Create schema for NFTCollection."""
    name: str = Field(..., min_length=3, max_length=100, description="Name of the NFT collection")
    symbol: str = Field(..., min_length=1, max_length=50, description="Symbol of the NFT collection")
    description: Optional[str] = Field(
        default=None,
        max_length=255,
        description="Description of the NFT collection",
    )
    image_url: Optional[str] = Field(default=None, description="URL of the collection's image")
    nft_count: int = Field(ge=1, description="Initial number of NFTs in the collection")
    
    class Config:
        schema_extra = {
            "example": {
                "name": "MyNFTCollection",
                "symbol": "MNFC",
                "description": "A collection of unique digital art.",
                "image_url": "https://example.com/mnfc.png",
                "nft_count": 100
            }
        }

class NFTCollectionUpdate(BaseModel):
    """Update schema for NFTCollection."""
    name: Optional[str] = Field(default=None, min_length=3, max_length=100, description="Name of the NFT collection")
    symbol: Optional[str] = Field(default=None, min_length=1, max_length=50, description="Symbol of the NFT collection")
    description: Optional[str] = Field(default=None, max_length=255, description="Description of the NFT collection")
    image_url: Optional[str] = Field(default=None, description="URL of the collection's image")
    nft_count: Optional[int] = Field(ge=1, description="Number of NFTs in the collection")
    
    class Config:
        schema_extra = {
            "example": {
                "name": "MyNFTCollection",
                "nft_count": 150
            }
        }

class NFTCollectionResponse(BaseModel):
    """Response schema for NFTCollection."""
    id: int
    name: str
    symbol: str
    description: Optional[str]
    image_url: Optional[str]
    nft_count: int

    class Config:
        schema_extra = {
            "example": {
                "id": 1,
                "name": "MyNFTCollection",
                "symbol": "MNFC",
                "description": "A collection of unique digital art.",
                "image_url": "https://example.com/mnfc.png",
                "nft_count": 150
            }
        }

class PortfolioCreate(BaseModel):
    """Create schema for Portfolio."""
    name: str = Field(..., min_length=3, max_length=100, description="Name of the portfolio")
    user_id: int = Field(..., description="ID of the user owning the portfolio")
    
    class Config:
        schema_extra = {
            "example": {
                "name": "MyPortfolio",
                "user_id": 1
            }
        }

class PortfolioUpdate(BaseModel):
    """Update schema for Portfolio."""
    name: Optional[str] = Field(default=None, min_length=3, max_length=100, description="Name of the portfolio")
    user_id: Optional[int] = Field(default=None, description="ID of the user owning the portfolio")
    
    class Config:
        schema_extra = {
            "example": {
                "name": "MyPortfolio"
            }
        }

class PortfolioResponse(BaseModel):
    """Response schema for Portfolio."""
    id: int
    name: str
    user_id: int

    class Config:
        schema_extra = {
            "example": {
                "id": 1,
                "name": "MyPortfolio",
                "user_id": 1
            }
        }

class NFTTransactionResponse(BaseModel):
    """Response schema for NFTTransaction."""
    id: int
    timestamp: datetime
    nft_id: int
    portfolio_id: int
    transaction_type: str
    amount: float
    price: float

    class Config:
        schema_extra = {
            "example": {
                "id": 1,
                "timestamp": datetime(2023, 10, 26, 10, 15, 0),
                "nft_id": 123,
                "portfolio_id": 456,
                "transaction_type": "buy",
                "amount": 0.5,
                "price": 100.0
            }
        }