/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTPosition {
  id: string;
  nftId: string;
  protocol: string;
  quantity: number;
  lastUpdated: string;
}

export interface RiskProfile {
  id: string;
  name: string;
  maxVolatility: number;
  liquidityThreshold: number;
}

export interface DeFiProtocol {
  id: string;
  name: string;
  apiEndpoint: string;
}

export interface RebalancingStrategy {
  id: string;
  protocol: string;
  newQuantity: number;
  timestamp: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
