/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface NFTHolder {
  id: string;
  nftAddress: string;
  preferences: any;
}

export interface Portfolio {
  id: string;
  nftHolderId: string;
  assetBalances: any;
}

export interface Asset {
  id: string;
  symbol: string;
  name: string;
}

export interface RebalancingRecommendation {
  id: string;
  portfolioId: string;
  recommendation: string;
  timestamp: string;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
