/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface SmartContract {
  contractAddress: string;
  contractName: string;
  contractVersion: string;
  creationTimestamp: string;
}

export interface VulnerabilityReport {
  id: string;
  contractAddress: string;
  vulnerabilityType: string;
  severity: string;
  description: string;
  confidenceScore: number;
  createdAt: string;
}

export interface RiskAssessment {
  id: string;
  contractAddress: string;
  assessmentTimestamp: string;
  overallRiskScore: number;
  riskFactors: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
