from sqlalchemy import Column, Integer, String, Float, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import back_populates
from uuid import uuid4
from datetime import datetime

Base = declarative_base()

class User(Base):
    """Represents a user of the Mossland Lending Protocol"""
    __tablename__ = 'users'

    id = Column(String, primary_key=True)
    username = Column(String, unique=True, nullable=False)
    risk_tolerance = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<User(id='{self.id}', username='{self.username}', risk_tolerance={self.risk_tolerance})>"


class SecurityToken(Base):
    """Represents a tokenized security asset"""
    __tablename__ = 'security_tokens'

    id = Column(String, primary_key=True)
    ticker = Column(String, nullable=False)
    name = Column(String, nullable=False)
    price = Column(Float, nullable=False)
    quantity = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<SecurityToken(id='{self.id}', ticker='{self.ticker}', name='{self.name}', price={self.price}, quantity={self.quantity})>"


class PortfolioPosition(Base):
    """Represents a position held within a portfolio"""
    __tablename__ = 'portfolio_positions'

    id = Column(String, primary_key=True)
    user_id = Column(String, nullable=False)
    security_token_id = Column(String, nullable=False)
    quantity = Column(Integer, nullable=False)
    entry_price = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<PortfolioPosition(id='{self.id}', user_id='{self.user_id}', security_token_id='{self.security_token_id}', quantity={self.quantity})>"

    back_populates = {'security_token': SecurityToken}


class RebalancingRecommendation(Base):
    """Recommendation generated by SynapseAI"""
    __tablename__ = 'rebalancing_recommendations'

    id = Column(String, primary_key=True)
    user_id = Column(String, nullable=False)
    security_token_id = Column(String, nullable=False)
    new_quantity = Column(Integer, nullable=False)
    reason = Column(String, nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def __repr__(self):
        return f"<RebalancingRecommendation(id='{self.id}', user_id='{self.user_id}', security_token_id='{self.security_token_id}', new_quantity={self.new_quantity})>"