/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface Agent {
  id: string;
  name: string;
  metadata: any;
  createdAt: string;
}

export interface Message {
  id: string;
  senderId: string;
  receiverId: string;
  content: string;
  createdAt: string;
}

export interface Transaction {
  id: string;
  timestamp: string;
  agentId: string;
  data: any;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
