/**
 * TypeScript Types - Generated by MOSS.AO
 */


export interface Portfolio {
  id: string;
  nftHolderAddress: string;
  createdAt: string;
  riskTolerance: string;
  currentAssets: any;
}

export interface RiskProfile {
  id: string;
  name: string;
  volatilityThreshold: number;
  maxDrawdown: number;
  assetAllocation: any;
}

export interface Strategy {
  id: string;
  name: string;
  parameters: any;
   SharpeRatio: number;
}


// API Response types
export interface ApiResponse<T> {
  data?: T;
  error?: string;
  status: number;
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}
